import express from "express";
import { getCurrentUser,otherUser,editProfile,getprofile,follow,searchUsers,getAllNotifications,readNotification } from "../controller/user.controller.js";
import isAuth from "../middleware/auth.middleware.js";
import upload from "../middleware/multer.middleware.js";
const Userrouter=express.Router();
Userrouter.get("/current",isAuth,getCurrentUser);
Userrouter.get("/other",isAuth,otherUser);
Userrouter.get("/search",isAuth,searchUsers);
Userrouter.post("/edit-profile",isAuth,upload.single("profilePic"),editProfile);
Userrouter.get("/profile/:username",isAuth,getprofile);
Userrouter.post("/follow/:userId",isAuth,follow);
Userrouter.get("/notifications",isAuth,getAllNotifications);
Userrouter.post("/notificationread",isAuth,readNotification);
export default Userrouter;